version: '3'  # Spécifie la version de la syntaxe Docker Compose

services:
  web:  # Définit un service nommé "web"
    build: .  # Construit l'image à partir du Dockerfile situé dans le répertoire actuel (.)
    
    ports:
      - "5000:5000"  # Mappe le port 5000 du conteneur au port 5000 de la machine hôte
    
    volumes:
      - .:/app  # Monte le répertoire actuel (.) sur "/app" dans le conteneur, permettant le hot-reloading (utile en dev)
